extends:
  - 'plugin:@autoguru/base'
  - 'plugin:@autoguru/react'
  - 'plugin:@autoguru/jest'

env:
  jest: true
  node: true
  browser: true

overrides:
  - files: '{*,{scripts,config}/**/*}.js'
    rules:
      '@typescript-eslint/require-await': 'off'
      '@typescript-eslint/no-var-requires': 'off'
      'unicorn/no-process-exit': 'off'
  - files: ['**/*.ts', '**/*.tsx']
    extends:
      - 'plugin:@autoguru/typescript'
    rules:
      'unicorn/consistent-function-scoping': 'off' # Yet
      '@typescript-eslint/prefer-optional-chain': 'error'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: ['./tsconfig.stories.json', './tsconfig.json']
