extends:
  - 'plugin:@autoguru/typescript'
  - 'plugin:@autoguru/react'
  - 'plugin:@autoguru/jest'

env:
  jest: true
  node: true
  browser: true

overrides:
  - files: '{*,{scripts,config}/**/*}.js'
    rules:
      '@typescript-eslint/require-await': 'off'
      '@typescript-eslint/no-var-requires': 'off'
      'unicorn/no-process-exit': 'off'
