language: node_js
cache: yarn
notifications:
  email: false
env:
  - TZ=Australia/Brisbane

jobs:
  include:
    - stage: test
      script: yarn test
      after_success: curl -s https://codecov.io/bash | bash
    - stage: deploy
      script: |
        if [ -n "$TRAVIS_PULL_REQUEST_SHA" ]; then
          npx surge -p ./storybook-static/ -d overdrive--${TRAVIS_PULL_REQUEST_SHA}.gh.autoguru.io
        elif [ "$TRAVIS_BRANCH" == "master" ]; then
          npx surge -p ./storybook-static/ -d overdrive.autoguru.io
        fi
